version: '3.4'

services:
  longnumberwebapi:
    image: longnumberwebapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
